name: Cypress Tests

on:
  push:
    branches:
      - 'githubActions_and_Allure'
  pull_request:
    branches:
      - 'githubActions_and_Allure'

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Actualizado a la versión más reciente

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Actualizado a la versión más reciente
        with:
          node-version: '20'  # Versión de Node.js que estás utilizando

      - name: Install dependencies
        run: npm install

      - name: Clear previous Allure reports
        run: npm run allure:clear

      - name: Run Cypress tests
        run: npm run ui-regression-allure

      - name: Generate Allure report
        run: npm run allure:report

      - name: Upload Allure report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report/
