name: Cypress Tests

on:
  push:
    branches:
      - 'githubActions_and _Allure'
  pull_request:
    branches:
      - 'githubActions_and_Allure'

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Cambia según la versión de Node que estés usando

      - name: Install dependencies
        run: npm install

      - name: Clear previous Allure reports
        run: npm run allure:clear

      - name: Run Cypress tests
        run: npm run ui-regression-allure # Ejecuta las pruebas con Allure habilitado

      - name: Generate Allure report
        run: npm run allure:report # Genera el informe de Allure

      - name: Upload Allure report
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: allure-report/ # Asegúrate de que esta ruta sea correcta
